### ISSUE TITLE
Should we reformat the mesheryctl command function to single function for adding the unit test cases

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery-tmp#11]

**Comment by Aisuko** [comment]
```package cmd

import (
	"fmt"
	"github.com/spf13/cobra"
)

func doSomething(cmd *cobra.Command, args []string) {
	return 1+1;
}

// caneCmd represents the cane command
var caneCmd = &cobra.Command{
	Use:   "cane",
	Short: "Ponder mysteries of the Horadrim",
	Long:  `Ponder mysteries of the Horadrim`,
	Run: doSomething,
}

func init() {
	rootCmd.AddCommand(caneCmd)
}
```

**Comment by leecalcote** [comment]
We do need a common convention for tests. 👍

**Comment by Aisuko** [comment]
I developed some util functions(Didn't change the original code just add the new util functions) for the `mesheryctl` unit test and the PR will coming quickly

**Comment by leecalcote** [comment]
@Aisuko do feel free to update `meshery-tmp` with a sync from `meshery`, if it helps.

**Comment by nveenjain** [comment]
Yes, this will be awesome. We should try to separate validating the arguments(length of arguments, range/format of arguments) logic with functional logic(calling some function) too, if we're planning to reformat every command..

**Comment by Aisuko** [comment]
@leecalcote That would be great. Is there a button that syncs to the latest code?🤣

**Comment by leecalcote** [comment]
Ha! This test / tmp is just that - - so blow away any content as you see fit. There's not guarantee of any thing in this repo. It was brought initially for testing of `mesheryctl` features, but has hung around for other tests.

**Comment by Aisuko** [comment]
Close because of #19
