### ISSUE TITLE
Upgrade the dependences of Meshery

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery-tmp#61]
**Description**

e.g:
 * ` proto.EnumName is deprecated: Do not use.  (SA1019)`
 * `package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)`

I saw lots of dependencies were deprecated in the newer version. So, we need to test it works well for meshery-tmp first and do PR to meshery.

**Expected Behavior**

* Upgrade the dependencies 
* Keep the upgrade effect can be control

**Screenshots**

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
Closing this bug on the `tmp` repo.
